services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pistachio
      POSTGRES_PASSWORD: pistachio_pwd
      POSTGRES_DB: pistachio_db
    ports:
      - "5432:5432"
